/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hiragana;

import java.awt.Font;
import static java.awt.font.TextAttribute.FONT;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author guilhermeteixeira
 */

public class Shuffler extends javax.swing.JFrame {
    
    
    
    /**
     * Creates new form hiraFrame
     */
    

    //String[][] romanji = Hiragana.romanji();
    String[][] hiragana = Hiragana.hiraganaWords(); //all words in hiragana
    
    String[][] hiraganaLetters = Hiragana.hiragana();//hiragana characters
    String[][] hiraganaRomanji = Hiragana.romanji();//hiragana characters in romanji
    
    String[][] katakana = Hiragana.katakana(); //katakana characters
    String[][] translation = Hiragana.translation(); // translation of all hiragana words to english
    
    String[][] kanji = Hiragana.kanji();
    String[][] kanjiMeaning = Hiragana.kanjiMeaning();
    
    boolean[] hiraganaBool = new boolean[hiragana.length];
    boolean[] kanjiBool = new boolean[kanji.length];
    
    
    ArrayList<String> toUse = new ArrayList<String>(); // array that stores all hiragana words

    ArrayList<String> meaning = new ArrayList<String>(); // array that stores all translated words
    
    int currentPosition = 0;
    int firstRun = 0;
    int lenArray;
    String currentChar = null;
    String reveal ="";
    String revealChar;
    String translatedChar;
    int revealList, revealIndex; 
    /*public class ExitThread extends Thread {
        public void addShutdownHook(ArrayList<String> wordsRomanji, ArrayList<String> wordsHiragana){
            try{
        FileOutputStream writeRomanji= new FileOutputStream("RomanjiWords");
        FileOutputStream writeHiragana= new FileOutputStream("HiraganaWords");
        ObjectOutputStream outRomanji= new ObjectOutputStream(writeRomanji);
        ObjectOutputStream outHiragana= new ObjectOutputStream(writeHiragana);
        outRomanji.writeObject(wordsRomanji);
        outHiragana.writeObject(wordsHiragana);
        outRomanji.close();
        outHiragana.close();
    }catch(IOException ioe){
        ioe.printStackTrace();
        }
        }
    }*/
    
    
    public Shuffler() {
        initComponents();
        
        /*try
        {
            FileInputStream readRoman = new FileInputStream("RomanjiWords");
            FileInputStream readHira = new FileInputStream("HiraganaWords");
            ObjectInputStream roma = new ObjectInputStream(readRoman);
            ObjectInputStream hira = new ObjectInputStream(readHira);
            wordsRomanji = (ArrayList) roma.readObject();
            wordsHiragana = (ArrayList) hira.readObject();
            roma.close();
            hira.close();
         }catch(IOException ioe){
             ioe.printStackTrace();
             return;
          }catch(ClassNotFoundException c){
             jTextField1.setText("File not found.");
             c.printStackTrace();
             return;
          }
    
    */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton28 = new javax.swing.JRadioButton();
        mainText = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        hiraganaRB = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        lastPosition = new javax.swing.JTextField();
        currPosition = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        revealButton = new javax.swing.JButton();
        translationText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jRadioButton28.setText("jRadioButton28");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainText.setEditable(false);
        mainText.setFont(new java.awt.Font("Yu Gothic", 1, 80)); // NOI18N
        mainText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainTextActionPerformed(evt);
            }
        });

        nextButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Settings"));

        hiraganaRB.setText("Hiragana");
        hiraganaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiraganaRBActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Shuffle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButton12.setText("Ch. 2 Vocab");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        jRadioButton18.setText("Ch. 1 Vocab");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });

        lastPosition.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastPosition.setText("0");
        lastPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastPositionActionPerformed(evt);
            }
        });

        currPosition.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        currPosition.setText("0");
        currPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currPositionActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Ch. 3 Vocab");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Katakana");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText("of");

        jRadioButton6.setText("Ch. 3 Kanji");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton7.setText("Ch. 4 Kanji");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton8.setText("Ch. 5 Kanji");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jRadioButton9.setText("Ch. 6 Kanji");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        jRadioButton10.setText("Ch. 7 Kanji");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        jRadioButton11.setText("Ch. 4 Vocab");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        jRadioButton13.setText("Ch. 5 Vocab");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        jRadioButton14.setText("Ch. 6 Vocab");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        jRadioButton15.setText("Ch. 7 Vocab");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });

        jRadioButton16.setText("Ch. 8 Vocab");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });

        jRadioButton17.setText("Ch. 8 Kanji");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });

        jRadioButton19.setText("Ch. 9 Vocab");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });

        jRadioButton20.setText("Ch. 9 Kanji");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });

        jRadioButton21.setText("Ch. 10 Vocab");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });

        jRadioButton22.setText("Ch. 10 Kanji");
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });

        jRadioButton23.setText("Ch. 11 Vocab");
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });

        jRadioButton24.setText("Ch. 12 Vocab");
        jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24ActionPerformed(evt);
            }
        });

        jRadioButton25.setText("Ch. 11 Kanji");
        jRadioButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton25ActionPerformed(evt);
            }
        });

        jRadioButton26.setText("Ch. 12 Kanji");
        jRadioButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton26ActionPerformed(evt);
            }
        });

        jRadioButton27.setText("All Vocab");
        jRadioButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton27ActionPerformed(evt);
            }
        });

        jRadioButton29.setText("All Kanji");
        jRadioButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton29ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(currPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(lastPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton11)
                            .addComponent(jRadioButton13)
                            .addComponent(jRadioButton14)
                            .addComponent(jRadioButton15)
                            .addComponent(jRadioButton16)
                            .addComponent(jRadioButton19)
                            .addComponent(jRadioButton21)
                            .addComponent(jRadioButton23)
                            .addComponent(jRadioButton18)
                            .addComponent(jRadioButton12)
                            .addComponent(jRadioButton27)
                            .addComponent(jRadioButton24))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton25)
                            .addComponent(jRadioButton22)
                            .addComponent(jRadioButton20)
                            .addComponent(jRadioButton17)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jRadioButton3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton29)
                                    .addComponent(hiraganaRB)))
                            .addComponent(jRadioButton26))))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton27)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton18)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton12)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton2)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton11)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton13)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton14)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton15)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton16)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton19)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton21)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton24)
                        .addGap(6, 6, 6)
                        .addComponent(currPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton29)
                        .addGap(6, 6, 6)
                        .addComponent(hiraganaRB)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton3)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton6)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton7)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton8)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton9)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton10)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton17)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton20)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton22)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton25)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton26)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(3, 3, 3)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(4, 4, 4))
        );

        revealButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        revealButton.setText("Reveal Japanese Word");
        revealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revealButtonActionPerformed(evt);
            }
        });

        translationText.setEditable(false);
        translationText.setFont(new java.awt.Font("Times New Roman", 1, 80)); // NOI18N
        translationText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Genki Textbook I Japanese letters, vocab, and kanji shuffler");

        jLabel3.setText("*Kanji expected");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                                .addComponent(mainText)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(translationText, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(revealButton, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(mainText, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(translationText, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(revealButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        if(currentPosition == toUse.size()) currentPosition = 0;
        if(meaning.get(currentPosition).length() >= 30){
            Font f = new Font("Times New Roman",Font.BOLD,30);
            translationText.setFont(f);
        }
        else if(meaning.get(currentPosition).length() >= 20){
            Font f = new Font("Times New Roman",Font.BOLD,45);
            translationText.setFont(f);
        }
        else if(meaning.get(currentPosition).length() == 1){
            Font f = new Font("Times New Roman",Font.BOLD,80);
            translationText.setFont(f);  
        }
        else{
            Font f = new Font("Times New Roman",Font.BOLD,60);
            translationText.setFont(f);
        }
        translationText.setText(String.valueOf(meaning.get(currentPosition)));
        currPosition.setText(String.valueOf(currentPosition+1));
        mainText.setText(String.valueOf(""));
        currentPosition++;
        
    }//GEN-LAST:event_nextButtonActionPerformed
    private void shuffleWords(){
        int newIndex;
        Random rand = new Random();
        String temp;
        for(int i = 0; i<toUse.size(); i++){
            newIndex = rand.nextInt(toUse.size()-1);
            temp = toUse.get(i);
            toUse.set(i,toUse.get(newIndex));
            toUse.set(newIndex, temp);
            
            temp = meaning.get(i);
            meaning.set(i,meaning.get(newIndex));
            meaning.set(newIndex, temp);
        }
    }    private static void add2ToUse(String[][] romanji, ArrayList<String> toUse){
        //this function will add the vowels/consonants to the list toUse so it can 
        //be iterated and displayed 
        
        for(int i = 0;i<=15;i++){
            for(int n = 0;n<romanji[i].length;n++){
                toUse.add(romanji[i][n]);
            }
        } 
    }    private void changeRadioButtons(boolean state){
        jRadioButton10.setSelected(state);
        jRadioButton11.setSelected(state);
        jRadioButton12.setSelected(state);
        jRadioButton13.setSelected(state);
        jRadioButton14.setSelected(state);
        jRadioButton15.setSelected(state);
        jRadioButton16.setSelected(state);
        jRadioButton17.setSelected(state);
        jRadioButton18.setSelected(state);
        jRadioButton19.setSelected(state);
        jRadioButton2.setSelected(state);
        jRadioButton20.setSelected(state);
        jRadioButton21.setSelected(state);
        jRadioButton22.setSelected(state);
        jRadioButton23.setSelected(state);
        jRadioButton24.setSelected(state);
        jRadioButton25.setSelected(state);
        jRadioButton26.setSelected(state);
        jRadioButton27.setSelected(state);
        jRadioButton28.setSelected(state);
        jRadioButton29.setSelected(state);
        jRadioButton6.setSelected(state);
        jRadioButton7.setSelected(state);
        jRadioButton8.setSelected(state);
        jRadioButton9.setSelected(state);
        if(!state){
            hiraganaRB.setSelected(state); 
            jRadioButton3.setSelected(state);    
            jRadioButton10.setEnabled(!state);
            jRadioButton11.setEnabled(!state);
            jRadioButton12.setEnabled(!state);
            jRadioButton13.setEnabled(!state);
            jRadioButton14.setEnabled(!state);
            jRadioButton15.setEnabled(!state);
            jRadioButton16.setEnabled(!state);
            jRadioButton17.setEnabled(!state);
            jRadioButton18.setEnabled(!state);
            jRadioButton19.setEnabled(!state);
            jRadioButton2.setEnabled(!state);
            jRadioButton20.setEnabled(!state);
            jRadioButton21.setEnabled(!state);
            jRadioButton22.setEnabled(!state);
            jRadioButton23.setEnabled(!state);
            jRadioButton24.setEnabled(!state);
            jRadioButton25.setEnabled(!state);
            jRadioButton26.setEnabled(!state);
            jRadioButton27.setEnabled(!state);
            jRadioButton28.setEnabled(!state);
            jRadioButton29.setEnabled(!state);
            jRadioButton3.setEnabled(!state);
            jRadioButton6.setEnabled(!state);
            jRadioButton7.setEnabled(!state);
            jRadioButton8.setEnabled(!state);
            jRadioButton9.setEnabled(!state);
            hiraganaRB.setEnabled(!state);
        }
    }private void changeRadioKanji(boolean state){
        jRadioButton6.setSelected(state);
        jRadioButton7.setSelected(state);
        jRadioButton8.setSelected(state);
        jRadioButton9.setSelected(state);
        jRadioButton10.setSelected(state);
        jRadioButton17.setSelected(state);
        jRadioButton20.setSelected(state);
        jRadioButton22.setSelected(state);
        jRadioButton25.setSelected(state);
        jRadioButton26.setSelected(state);
        if(state){
            jRadioButton6.setEnabled(!state);
            jRadioButton7.setEnabled(!state);
            jRadioButton8.setEnabled(!state);
            jRadioButton9.setEnabled(!state);
            jRadioButton10.setEnabled(!state);
            jRadioButton17.setEnabled(!state);
            jRadioButton20.setEnabled(!state);
            jRadioButton22.setEnabled(!state);
            jRadioButton25.setEnabled(!state);
            jRadioButton26.setEnabled(!state);
            jRadioButton29.setEnabled(!state);
        }
    }
    private void changeRadioVocab(boolean state){
        jRadioButton11.setSelected(state);
        jRadioButton12.setSelected(state);
        jRadioButton13.setSelected(state);
        jRadioButton14.setSelected(state);
        jRadioButton15.setSelected(state);
        jRadioButton16.setSelected(state);
        jRadioButton18.setSelected(state);
        jRadioButton19.setSelected(state);
        jRadioButton2.setSelected(state);
        jRadioButton21.setSelected(state);
        jRadioButton23.setSelected(state);
        jRadioButton24.setSelected(state);
        jRadioButton27.setSelected(state);
        jRadioButton28.setSelected(state);
        if(state){
        jRadioButton11.setEnabled(!state);
        jRadioButton12.setEnabled(!state);
        jRadioButton13.setEnabled(!state);
        jRadioButton14.setEnabled(!state);
        jRadioButton15.setEnabled(!state);
        jRadioButton16.setEnabled(!state);
        jRadioButton18.setEnabled(!state);
        jRadioButton19.setEnabled(!state);
        jRadioButton2.setEnabled(!state);
        jRadioButton21.setEnabled(!state);
        jRadioButton23.setEnabled(!state);
        jRadioButton24.setEnabled(!state);
        jRadioButton27.setEnabled(!state);
        jRadioButton28.setEnabled(!state);
        }
    }
    private void revealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revealButtonActionPerformed
        // TODO add your handling code here:
        if(currentPosition>0){
            if(toUse.get(currentPosition-1).length()>7){
                Font f = new Font("Times New Roman",Font.BOLD,60);
                mainText.setFont(f);
            }
            else{
                Font f = new Font("Times New Roman",Font.BOLD,80);
                mainText.setFont(f);
            }
            mainText.setText(String.valueOf(toUse.get(currentPosition-1)));
        }
        
    }//GEN-LAST:event_revealButtonActionPerformed

    private void mainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainTextActionPerformed

    private void jRadioButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton29ActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < kanji.length ; i++){
            for(int n = 0 ; n < kanji[i].length ; n++){ 
                if(kanjiBool[i]) break;
                    toUse.add(kanji[i][n]);
                    meaning.add(kanjiMeaning[i][n]);
                }
               kanjiBool[i] = true;
        }
        changeRadioKanji(true);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        lastPosition.setText(String.valueOf(toUse.size()));
        shuffleWords();
    }//GEN-LAST:event_jRadioButton29ActionPerformed

    private void jRadioButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton27ActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < hiragana.length ; i++){
            for(int n = 0 ; n < hiragana[i].length ; n++){ 
                if(hiraganaBool[i]) break;
                    toUse.add(hiragana[i][n]);
                    meaning.add(translation[i][n]);
                }
               hiraganaBool[i] = true;
        }
        lastPosition.setText(String.valueOf(toUse.size()));
        changeRadioVocab(true);
        lastPosition.setText(String.valueOf(toUse.size()));
        currPosition.setText(String.valueOf(0));
        currentPosition = 0;
        shuffleWords();

    }//GEN-LAST:event_jRadioButton27ActionPerformed

    private void jRadioButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton26ActionPerformed
        // TODO add your handling code here:
        for(String s: kanji[12]) toUse.add(s);
        for(String s:kanjiMeaning[12]) meaning.add(s);
        kanjiBool[12] = true;
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton26.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
    }//GEN-LAST:event_jRadioButton26ActionPerformed

    private void jRadioButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton25ActionPerformed
        // TODO add your handling code here:
        for(String s: kanji[11]) toUse.add(s);
        for(String s:kanjiMeaning[11]) meaning.add(s);
        kanjiBool[11] = true;
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton25.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
    }//GEN-LAST:event_jRadioButton25ActionPerformed

    private void jRadioButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24ActionPerformed
        // TODO add your handling code here:
        hiraganaBool[12] = true;
        for(String s:hiragana[12]) toUse.add(s);
        for(String s:translation[12]) meaning.add(s);
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton24.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        shuffleWords();
    }//GEN-LAST:event_jRadioButton24ActionPerformed

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
        // TODO add your handling code here:
        hiraganaBool[11] = true;
        for(String s:hiragana[11]) toUse.add(s);
        for(String s:translation[11]) meaning.add(s);
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton23.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        shuffleWords();
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
        // TODO add your handling code here:
        for(String s: kanji[10]) toUse.add(s);
        for(String s:kanjiMeaning[10]) meaning.add(s);
        kanjiBool[10] = true;
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton22.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
    }//GEN-LAST:event_jRadioButton22ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
        // TODO add your handling code here:
        hiraganaBool[10] = true;
        for(String s:hiragana[10]) toUse.add(s);
        for(String s:translation[10]) meaning.add(s);
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton21.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        shuffleWords();
    }//GEN-LAST:event_jRadioButton21ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        // TODO add your handling code here:
        for(String s: kanji[9]) toUse.add(s);
        for(String s:kanjiMeaning[9]) meaning.add(s);
        kanjiBool[9] = true;
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton20.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        // TODO add your handling code here:
        hiraganaBool[9] = true;
        for(String s:hiragana[9]) toUse.add(s);
        for(String s:translation[9]) meaning.add(s);
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton19.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        shuffleWords();
    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        // TODO add your handling code here:
        for(String s: kanji[8]) toUse.add(s);
        for(String s:kanjiMeaning[8]) meaning.add(s);
        kanjiBool[8] = true;
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton17.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        // TODO add your handling code here:
        
        hiraganaBool[8] = true;
        for(String s:hiragana[8]) toUse.add(s);
        for(String s:translation[8]) meaning.add(s);
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton16.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        shuffleWords();
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // TODO add your handling code here:
        hiraganaBool[7] = true;
        for(String s:hiragana[7]) toUse.add(s);
        for(String s:translation[7]) meaning.add(s);
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton15.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        shuffleWords();
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
        hiraganaBool[6] = true;
        for(String s:hiragana[6]) toUse.add(s);
        for(String s:translation[6]) meaning.add(s);
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton14.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        shuffleWords();
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // TODO add your handling code here:
        
        hiraganaBool[5] = true;
        for(String s:hiragana[5]) toUse.add(s);
        for(String s:translation[5]) meaning.add(s);
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton13.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        shuffleWords();
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
        hiraganaBool[4] = true;
        for(String s:hiragana[4]) toUse.add(s);
        for(String s:translation[4]) meaning.add(s);
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton11.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        shuffleWords();
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
        for(String s: kanji[7]) toUse.add(s);
        for(String s:kanjiMeaning[7]) meaning.add(s);
        kanjiBool[7] = true;
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton10.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
        for(String s: kanji[6]) toUse.add(s);
        for(String s:kanjiMeaning[6]) meaning.add(s);
        kanjiBool[6] = true;
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton9.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
        for(String s: kanji[5]) toUse.add(s);
        for(String s:kanjiMeaning[5]) meaning.add(s);
        kanjiBool[5] = true;
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton8.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        for(String s: kanji[4]) toUse.add(s);
        kanjiBool[4] = true;
        for(String s:kanjiMeaning[4]) meaning.add(s);
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton7.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        for(String s: kanji[3]) toUse.add(s);
        for(String s:kanjiMeaning[3]) toUse.add(s);
        kanjiBool[3] = true;
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton6.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        jRadioButton3.setEnabled(false);
        for(String[] arrS:katakana){
            for(String s: arrS){
                toUse.add(s);
            }
        }
        for(String[] arrS:hiraganaRomanji){
            for(String s: arrS){
                meaning.add(s);
            }
        }
        lastPosition.setText(String.valueOf(toUse.size()));
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        shuffleWords();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        hiraganaBool[3] = true;
        for(String s:hiragana[3]) toUse.add(s);
        for(String s:translation[3]) meaning.add(s);
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton2.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        shuffleWords();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void currPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currPositionActionPerformed

    private void lastPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastPositionActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        // TODO add your handling code here:
        hiraganaBool[1] = true;
        for(String s:hiragana[1]) toUse.add(s);
        for(String s:translation[1]) meaning.add(s);
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton18.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        shuffleWords();
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
        hiraganaBool[2] = true;
        for(String s:hiragana[2]) toUse.add(s);
        for(String s:translation[2]) meaning.add(s);
        lastPosition.setText(String.valueOf(toUse.size()));
        jRadioButton12.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        shuffleWords();
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        shuffleWords();
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        toUse.clear();
        meaning.clear();
        changeRadioButtons(false);
        currPosition.setText(String.valueOf(0));
        lastPosition.setText(String.valueOf(0));
        mainText.setText(String.valueOf(""));
        translationText.setText(String.valueOf(""));
        currentPosition = 0;
        hiraganaBool = new boolean[hiragana.length];
        kanjiBool = new boolean[kanji.length];
    }//GEN-LAST:event_jButton3ActionPerformed

    private void hiraganaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiraganaRBActionPerformed
        // TODO add your handling code here:
        for(String[] s:hiraganaLetters){
            for(String letter:s){
                toUse.add(letter);
            }
        }
        for(String[] s:hiraganaRomanji){
            for(String letter:s){
                meaning.add(letter);
            }
        }
        //currPosition.setText(String.valueOf(currentPosition));
        lastPosition.setText(String.valueOf(toUse.size()));
        hiraganaRB.setEnabled(false);
        currentPosition = 0;
        currPosition.setText(String.valueOf(0));
        shuffleWords();
    }//GEN-LAST:event_hiraganaRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shuffler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shuffler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shuffler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shuffler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shuffler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField currPosition;
    private javax.swing.JRadioButton hiraganaRB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField lastPosition;
    private javax.swing.JTextField mainText;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton revealButton;
    private javax.swing.JTextField translationText;
    // End of variables declaration//GEN-END:variables
}
